CREATE PROCEDURE GET_RETAINED_CUSTOMERS
    @MIN_ORDERS INT
AS
BEGIN
    -- TOTAL NUMBER OF CUSTOMERS
    DECLARE @TOTAL_CUSTOMERS INT;
    SELECT @TOTAL_CUSTOMERS = COUNT(DISTINCT CUSTOMERID) FROM FACTSALES;

    -- CUSTOMERS WHO PLACED AT LEAST @MIN_ORDERS ORDERS
    SELECT CUSTOMERID, COUNT(ORDERID) AS ORDER_COUNT
    FROM FACTSALES
    GROUP BY CUSTOMERID
    HAVING COUNT(ORDERID) >= @MIN_ORDERS;

    -- PERCENTAGE OF CUSTOMERS MEETING THE MIN_ORDERS THRESHOLD
    SELECT 
        (COUNT(DISTINCT CUSTOMERID) * 100.0 / @TOTAL_CUSTOMERS) AS RETENTION_PERCENTAGE
    FROM FACTSALES
    WHERE CUSTOMERID IN (
        SELECT CUSTOMERID FROM FACTSALES 
        GROUP BY CUSTOMERID
        HAVING COUNT(ORDERID) >= @MIN_ORDERS
    );
END;
