CREATE PROCEDURE GET_SALES_BY_CATEGORY_REGION
    @START_DATE DATE, 
    @END_DATE DATE
AS
BEGIN
    SELECT P.CATEGORY, S.REGION, 
           SUM(F.TOTALAMOUNT) AS TOTAL_SALES, 
           AVG(F.TOTALAMOUNT) AS AVG_SALES
    FROM FACTSALES F
    JOIN DIMPRODUCTS P ON F.PRODUCTID = P.PRODUCTID
    JOIN DIMSTORES S ON F.STOREID = S.STOREID
    JOIN DIMDATES D ON F.DATEID = D.DATEID
    WHERE D.FULLDATE BETWEEN @START_DATE AND @END_DATE
    GROUP BY P.CATEGORY, S.REGION;
END;
