CREATE PROCEDURE GET_PAYMENT_DISTRIBUTION
AS
BEGIN
    DECLARE @TOP_REGION NVARCHAR(50);

    -- IDENTIFY THE REGION WITH HIGHEST TOTAL REVENUE
    SELECT TOP 1 @TOP_REGION = S.REGION
    FROM FACTSALES F
    JOIN DIMSTORES S ON F.STOREID = S.STOREID
    GROUP BY S.REGION
    ORDER BY SUM(F.TOTALAMOUNT) DESC;

    -- PAYMENT METHOD DISTRIBUTION IN TOP REGION
    SELECT O.PAYMENTMETHOD, COUNT(*) AS PAYMENT_COUNT,
           (COUNT(*) * 100.0 / SUM(COUNT(*)) OVER()) AS PERCENTAGE
    FROM FACTSALES F
    JOIN ORDERS O ON F.ORDERID = O.ORDERID
    JOIN DIMSTORES S ON F.STOREID = S.STOREID
    WHERE S.REGION = @TOP_REGION
    GROUP BY O.PAYMENTMETHOD;
END;
