CREATE PROCEDURE GETSALESSUMMARY
    @START_DATE DATE, 
    @END_DATE DATE
AS
BEGIN
    -- TOTAL AND AVERAGE SALES BY DAY
    SELECT D.FULLDATE, 
           SUM(F.TOTALAMOUNT) AS TOTAL_SALES, 
           AVG(F.TOTALAMOUNT) AS AVG_SALES
    FROM FACTSALES F
    JOIN DIMDATES D ON F.DATEID = D.DATEID
    WHERE D.FULLDATE BETWEEN @START_DATE AND @END_DATE
    GROUP BY D.FULLDATE;

    -- TOTAL AND AVERAGE SALES BY MONTH
    SELECT D.YEAR, D.MONTH, 
           SUM(F.TOTALAMOUNT) AS TOTAL_SALES, 
           AVG(F.TOTALAMOUNT) AS AVG_SALES
    FROM FACTSALES F
    JOIN DIMDATES D ON F.DATEID = D.DATEID
    WHERE D.FULLDATE BETWEEN @START_DATE AND @END_DATE
    GROUP BY D.YEAR, D.MONTH;

    -- TOTAL AND AVERAGE SALES BY YEAR
    SELECT D.YEAR, 
           SUM(F.TOTALAMOUNT) AS TOTAL_SALES, 
           AVG(F.TOTALAMOUNT) AS AVG_SALES
    FROM FACTSALES F
    JOIN DIMDATES D ON F.DATEID = D.DATEID
    WHERE D.FULLDATE BETWEEN @START_DATE AND @END_DATE
    GROUP BY D.YEAR;
END;
